version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cnpj-api-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1779nar669gee"
s3_prefix = "cnpj-api-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"


